"""Independent wiretap for LP-1 latent traffic.

Trains a small decoder that reads the sender's slot vectors directly — neither
the sender's internals nor the Qwen receiver are consulted at decode time, and
the receiver is never even loaded during training. Decode accuracy comparable to
the receiver's proves the wire is readable without asking either mind.

Ships two trust gauges:
- confidence: mean max-softmax over characters (calibration reported per bin);
- on-manifold z: per-slot Gaussian fit of training traffic; traffic from a
  different protocol (another sender) or jamming (noise) should score high z,
  turning silent mistranslation into a detectable event.
"""

from __future__ import annotations

import argparse
import json
import time
from pathlib import Path

import numpy as np
import torch
from torch import nn

from .latent_port import BASE32_ALPHABET, LatentSender, payload_to_bits, random_payload


def sender_config(state: dict) -> tuple[int, int, int, int]:
    """Infer (slots, chars_per_slot, hidden, d_model) from a sender checkpoint."""
    slots = state["slot_pos"].shape[0]
    hidden = state["embed.0.weight"].shape[0]
    chars_per_slot = state["embed.0.weight"].shape[1] // 5
    d_model = state["out.weight"].shape[0]
    return slots, chars_per_slot, hidden, d_model


def load_sender(checkpoint: Path, device: str) -> tuple[LatentSender, int, int]:
    state = torch.load(checkpoint, map_location=device)
    slots, chars_per_slot, hidden, d_model = sender_config(state)
    sender = LatentSender(slots, chars_per_slot, d_model, embed_rms=0.0, hidden=hidden)
    sender.load_state_dict(state)
    sender = sender.to(device).eval()
    for parameter in sender.parameters():
        parameter.requires_grad_(False)
    return sender, slots, chars_per_slot


class Wiretap(nn.Module):
    """Slot vectors -> per-character 32-way logits. No language model involved."""

    def __init__(self, d_model: int, chars_per_slot: int, width: int = 256, layers: int = 2) -> None:
        super().__init__()
        self.chars_per_slot = chars_per_slot
        self.inlet = nn.Sequential(nn.LayerNorm(d_model), nn.Linear(d_model, width), nn.GELU())
        block = nn.TransformerEncoderLayer(
            width, 8, width * 4, dropout=0.0, batch_first=True, norm_first=True
        )
        self.mixer = nn.TransformerEncoder(block, layers)
        self.heads = nn.Linear(width, chars_per_slot * 32)

    def forward(self, latents: torch.Tensor) -> torch.Tensor:
        mixed = self.mixer(self.inlet(latents))
        batch, slots, _ = latents.shape
        return self.heads(mixed).reshape(batch, slots, self.chars_per_slot, 32)


def batch_payloads(characters: int, batch: int, rng: np.random.Generator) -> list[str]:
    return [random_payload(characters, rng) for _ in range(batch)]


def payload_targets(payloads: list[str], slots: int, device: str) -> torch.Tensor:
    indices = torch.tensor(
        [[BASE32_ALPHABET.index(c) for c in payload] for payload in payloads], device=device
    )
    return indices.reshape(len(payloads), slots, -1)


@torch.no_grad()
def traffic(sender: LatentSender, payloads: list[str], slots: int, device: str) -> torch.Tensor:
    bits = torch.from_numpy(np.stack([payload_to_bits(p, slots) for p in payloads])).to(device)
    return sender(bits).float()


def sender_traffic_fn(sender: LatentSender, slots: int, device: str):
    return lambda payloads: traffic(sender, payloads, slots, device)


def bridge_traffic_fn(checkpoint: Path, sender_model_id: str, device: str):
    """Traffic generated by an LP-3 bridge reading a frozen A-model's states."""
    from .latent_bridge import ABrain, GatherBridge, a_text, payload_offset

    state = torch.load(checkpoint, map_location=device)
    slots = state["slot_pos"].shape[0]
    hidden = state["embed.0.weight"].shape[0]
    d_model = state["out.weight"].shape[0]
    brain = ABrain(sender_model_id, device)
    chars_per_slot = state["embed.0.weight"].shape[1] // brain.width
    bridge = GatherBridge(
        brain.width, d_model, slots, chars_per_slot, 0.0,
        offset=payload_offset(brain), hidden=hidden,
    )
    bridge.load_state_dict(state)
    bridge = bridge.to(device).eval()
    for parameter in bridge.parameters():
        parameter.requires_grad_(False)

    @torch.no_grad()
    def fn(payloads: list[str]) -> torch.Tensor:
        states, mask = brain.read([a_text(p) for p in payloads])
        return bridge(states, mask).float()

    return fn, slots, chars_per_slot


@torch.no_grad()
def read_wire(tap: Wiretap, latents: torch.Tensor) -> tuple[list[str], torch.Tensor]:
    logits = tap(latents)
    probabilities = logits.softmax(dim=-1)
    confidence = probabilities.max(dim=-1).values.mean(dim=(1, 2))
    picks = logits.argmax(dim=-1)
    decoded = [
        "".join(BASE32_ALPHABET[i] for i in sample.reshape(-1).tolist()) for sample in picks
    ]
    return decoded, confidence


class ManifoldGauge:
    """Per-slot diagonal Gaussian of legitimate traffic; z ~ 1 in-distribution."""

    def __init__(self, latents: torch.Tensor) -> None:
        self.mean = latents.mean(dim=0, keepdim=True)
        self.std = latents.std(dim=0, keepdim=True).clamp_min(1e-6)

    def z(self, latents: torch.Tensor) -> torch.Tensor:
        return (((latents - self.mean) / self.std) ** 2).mean(dim=(1, 2)).sqrt()


def train_tap(traffic_fn, slots: int, chars_per_slot: int, args, characters: int) -> tuple[Wiretap, ManifoldGauge]:
    torch.manual_seed(args.seed + characters)
    d_model = traffic_fn(["A" * characters]).shape[-1]
    tap = Wiretap(d_model, chars_per_slot, width=args.width).to(args.device)
    optimizer = torch.optim.AdamW(tap.parameters(), lr=args.lr)
    loss_fn = nn.CrossEntropyLoss()
    started = time.monotonic()
    for step in range(args.steps):
        rng = np.random.default_rng(args.seed * 611_953 + characters * 7 + step)
        payloads = batch_payloads(characters, args.batch_size, rng)
        latents = traffic_fn(payloads)
        logits = tap(latents)
        targets = payload_targets(payloads, slots, args.device)
        loss = loss_fn(logits.reshape(-1, 32), targets.reshape(-1))
        optimizer.zero_grad(set_to_none=True)
        loss.backward()
        optimizer.step()
        if step % 500 == 0 or step == args.steps - 1:
            print(
                f"  {characters} chars: tap step {step}/{args.steps} "
                f"loss={loss.item():.4f} ({time.monotonic() - started:.0f}s)",
                flush=True,
            )
    calibration_rng = np.random.default_rng(args.seed * 104_729 + characters)
    gauge = ManifoldGauge(traffic_fn(batch_payloads(characters, 512, calibration_rng)))
    return tap, gauge


@torch.no_grad()
def evaluate_tap(tap, gauge, traffic_fn, slots: int, args, characters: int) -> dict:
    # Identical payload stream to LP-1's held-out evals: tap and receiver are
    # scored on the same messages.
    exact = 0
    char_hits = 0
    confidences = []
    zs = []
    bins: dict[str, list[float]] = {}
    for index in range(args.eval_samples):
        rng = np.random.default_rng(args.lp1_seed * 7919 + 777_000 + index)
        payload = random_payload(characters, rng)
        latents = traffic_fn([payload])
        decoded, confidence = read_wire(tap, latents)
        z = gauge.z(latents)
        hits = sum(a == b for a, b in zip(decoded[0], payload))
        exact += decoded[0] == payload
        char_hits += hits
        confidences.append(float(confidence[0]))
        zs.append(float(z[0]))
        bin_key = f"{min(int(confidence[0] * 10), 9) / 10:.1f}"
        bins.setdefault(bin_key, []).append(hits / characters)
    return {
        "tap_exact_rate": exact / args.eval_samples,
        "tap_char_accuracy": char_hits / (characters * args.eval_samples),
        "mean_confidence": float(np.mean(confidences)),
        "mean_z": float(np.mean(zs)),
        "calibration_bins": {k: round(float(np.mean(v)), 4) for k, v in sorted(bins.items())},
    }


@torch.no_grad()
def ood_report(tap, gauge, traffic_fn, other_traffic_fns, slots: int, args, characters: int) -> list[dict]:
    """Confidence/z for legitimate, drifted (other protocol), and jammed traffic."""
    rng = np.random.default_rng(args.seed * 15_485_863 + characters)
    rows = []
    own = traffic_fn(batch_payloads(characters, 64, rng))
    _, confidence = read_wire(tap, own)
    rows.append({
        "traffic": "own protocol",
        "mean_confidence": float(confidence.mean()),
        "mean_z": float(gauge.z(own).mean()),
    })
    for other_chars, other_fn in other_traffic_fns.items():
        if other_chars == characters:
            continue
        other_latents = other_fn(batch_payloads(abs(other_chars), 64, rng))
        _, confidence = read_wire(tap, other_latents)
        rows.append({
            "traffic": f"drifted protocol ({abs(other_chars)}-char {'LP-1 sender' if other_chars < 0 else 'sender'})",
            "mean_confidence": float(confidence.mean()),
            "mean_z": float(gauge.z(other_latents).mean()),
        })
    noise = torch.randn_like(own) * own.pow(2).mean().sqrt()
    _, confidence = read_wire(tap, noise)
    rows.append({
        "traffic": "noise (jamming)",
        "mean_confidence": float(confidence.mean()),
        "mean_z": float(gauge.z(noise).mean()),
    })
    return rows


def parse_ints(value: str) -> list[int]:
    return sorted({int(item) for item in value.split(",")})


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--chars", type=parse_ints, default=parse_ints("16,32,48,64"))
    parser.add_argument("--source", choices=("sender", "bridge"), default="sender")
    parser.add_argument("--bridge-checkpoint", type=Path, default=Path("runs/bridges/lp3_32chars_16slots.pt"))
    parser.add_argument("--bridge-sender-model", default="Qwen/Qwen3-0.6B")
    parser.add_argument("--slots", type=int, default=16)
    parser.add_argument("--width", type=int, default=256)
    parser.add_argument("--steps", type=int, default=4000)
    parser.add_argument("--batch-size", type=int, default=64)
    parser.add_argument("--lr", type=float, default=1e-3)
    parser.add_argument("--eval-samples", type=int, default=64)
    parser.add_argument("--seed", type=int, default=20260811)
    parser.add_argument("--lp1-seed", type=int, default=20260810)
    parser.add_argument("--device", default="cuda")
    parser.add_argument("--checkpoint-dir", type=Path, default=Path("runs/senders"))
    parser.add_argument("--lp1-results", type=Path, default=Path("runs/latent_port.json"))
    parser.add_argument("--output", type=Path, default=Path("runs/wiretap.json"))
    args = parser.parse_args()

    receiver_scores = {}
    # Only attach LP-1 direct-sender receiver scores in sender mode. In bridge
    # mode the receiver is the LP-3 bridge (different artifact); pulling from
    # latent_port.json here would mislabel the bridge's receiver score.
    if args.source == "sender" and args.lp1_results.exists():
        for row in json.loads(args.lp1_results.read_text())["results"]:
            receiver_scores[row["characters"]] = {
                "receiver_exact_rate": row["exact_rate"],
                "receiver_char_accuracy": row["char_accuracy"],
            }

    traffic_fns = {}
    if args.source == "bridge":
        fn, slots, chars_per_slot = bridge_traffic_fn(
            args.bridge_checkpoint, args.bridge_sender_model, args.device
        )
        args.slots = slots
        args.chars = [slots * chars_per_slot]
        traffic_fns[args.chars[0]] = fn
        # Drifted-protocol reference: the LP-1 sender at the same load, if present.
        lp1 = args.checkpoint_dir / f"lp1_{args.chars[0]}chars_{slots}slots.pt"
        if lp1.exists():
            traffic_fns[-args.chars[0]] = sender_traffic_fn(
                load_sender(lp1, args.device)[0], slots, args.device
            )
    else:
        for characters in args.chars:
            checkpoint = args.checkpoint_dir / f"lp1_{characters}chars_{args.slots}slots.pt"
            traffic_fns[characters] = sender_traffic_fn(
                load_sender(checkpoint, args.device)[0], args.slots, args.device
            )

    results = []
    for characters in args.chars:
        traffic_fn = traffic_fns[characters]
        print(f"== wiretap on the {characters}-char {args.source} ==", flush=True)
        tap, gauge = train_tap(traffic_fn, args.slots, characters // args.slots, args, characters)
        scores = evaluate_tap(tap, gauge, traffic_fn, args.slots, args, characters)
        ood = ood_report(tap, gauge, traffic_fn, traffic_fns, args.slots, args, characters)
        tap_name = f"tap_{args.source}_{characters}chars.pt" if args.source == "bridge" else f"tap_{characters}chars.pt"
        checkpoint = args.output.parent / "wiretaps" / tap_name
        checkpoint.parent.mkdir(parents=True, exist_ok=True)
        torch.save(tap.state_dict(), checkpoint)
        result = {
            "source": args.source,
            "characters": characters,
            "slots": args.slots,
            "loaded_bits_per_slot": 5 * characters / args.slots,
            "tap_parameters": sum(p.numel() for p in tap.parameters()),
            **scores,
            **receiver_scores.get(characters, {}),
            "ood": ood,
            "tap_checkpoint": str(checkpoint),
        }
        results.append(result)
        print(json.dumps(result, sort_keys=True), flush=True)
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(json.dumps({"experiment": "LP-1 wiretap", "results": results}, indent=2) + "\n")


if __name__ == "__main__":
    main()
